---
# BEGIN
server:
  port : 7070
  logging:
    level:
      root: "warn"
      org.springframework.web: "debug"
      org.hibernate: "error"
# END

users:
  admins:
    - gjoinsey1@blogger.com
    - scrosi4@cam.ac.uk
    - brundle@cam.ac.uk

